### ISSUE TITLE
missing defaultHttpConfig

### ISSUE THREAD

**Issue by angel-popov** [mrkkrp/req#65]
Hi, 
I am trying example from readme and it failed with:
    Variable not in scope: defaultHttpConfig :: HttpConfig
   |
12 | main = runReq defaultHttpConfig $ do
   |               ^^^^^^^^^^^^^^^^^
Failed, no modules loaded.

It is stack based project and i have these in the dependencies:
library:
  source-dirs: src
  dependencies:
    - mtl
    - validation
    - optparse-applicative
    - req
    - aeson

**Comment by mrkkrp** [comment]
Which version of `req` do you use?

**Comment by mrkkrp** [comment]
Apparently Stackgage has a very ancient version of Req right now. It should be updated now. In the meantime, something like this could get you the latest version:

```yaml
resolver: lts-13.16
packages:
- '.'
extra-deps:
- req-2.0.1
- retry-0.8.0.1
```
